<?php


class MoveablePoint extends Point
{
private float $xSpeed;
private float $ySpeed;
public function __construct(float $x, float $y, float $xSpeed, float $ySpeed)
{
    parent::__construct($x, $y);
    $this->xSpeed = $xSpeed;
    $this->ySpeed = $ySpeed;
}
public function __toString(): string
{
    return parent::__toString() . "Speed X = " . $this->xSpeed . "<br/>" . "Speed Y = " . $this->ySpeed . "<br/>"; // TODO: Change the autogenerated stub
}

    /**
     * @return float
     */
    public function getXSpeed(): float
    {
        return $this->xSpeed;
    }

    /**
     * @param float $xSpeed
     */
    public function setXSpeed(float $xSpeed): void
    {
        $this->xSpeed = $xSpeed;
    }

    /**
     * @return float
     */
    public function getYSpeed(): float
    {
        return $this->ySpeed;
    }

    /**
     * @param float $ySpeed
     */
    public function setYSpeed(float $ySpeed): void
    {
        $this->ySpeed = $ySpeed;
    }
    public function getSpeed(): array {
        $arr = [];
        array_push($arr, $this->xSpeed, $this->ySpeed);
        return $arr;
    }
    public function move(): MoveablePoint {
        $this->x += $this->xSpeed;
        $this->y += $this->ySpeed;
    }
}