<?php


class Cylinder extends Circle
{
    private $height;

    public function __construct($radius, $color, $height)
    {
        parent::__construct($radius, $color);
        $this->height = $height;
    }

    public function __toString()
    {
        return parent::__toString() . "Height: " . $this->height . "<br/>"; // TODO: Change the autogenerated stub

    }

    public function calculateVolume()
    {
        return parent::calculateArea() * $this->height;
    }
}