<?php


class Point3D extends Point2D
{
    protected $z;

    public function __construct(float $x, float $y, float $z)
    {
        parent::__construct($x, $y);
        $this->z = $z;
    }

    public function __toString(): string
    {
        return parent::__toString() . "Z = " . $this->z . "<br/>"; // TODO: Change the autogenerated stub
    }

    /**
     * @return float
     */
    public function getZ(): float
    {
        return $this->z;
    }

    /**
     * @param float $z
     */
    public function setZ(float $z): void
    {
        $this->z = $z;
    }

    public function setXYZ(float $x, float $y, float $z): void
    {
        $this->x = $x;
        $this->y = $y;
        $this->z = $z;
    }

    public function getXYZ(): string
    {
        $arr = [];
        array_push($arr, $this->x, $this->y, $this->z);
        return $arr;
    }
}